AllCops:
  TargetRubyVersion: 2.4.1
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/FileName:
  Exclude:
    - Gemfile
